server:
  port: 8082

spring:
  application:
    name: summer-cloud-ai-service-mcp-server

  ai:
    mcp:
      server:
        enabled: true
        name: mcp-server-weather
        version: 1.0.0
        type: SYNC # SYNC表示同步调用 ASYNC表示异步调用
