server:
  port: 8081

spring:
  application:
    name: summer-cloud-ai-service-chat

  elasticsearch:
    uris: http://localhost:9200
    username:
    password:

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: root
      timeout: 5000
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-wait: 5000
          min-idle: 5
          max-idle: 10
          time-between-eviction-runs: 1000

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/summer-cloud-platform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: ${LOCAL_MYSQL_PASSWORD}
    hikari:
      #连接超时时间,小于250毫秒,否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间,默认值600000单位毫秒,大于等于max-lifetime且max-lifetime>0,会被重置为0,不等于0且小于10秒,会被重置为10秒
      idle-timeout: 500000
      #连接最大存活时间,不等于0且小于30秒,会被重置为默认值30分钟,设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #最小空闲连接,默认值10,小于0或大于maximum-pool-size,都会重置为maximum-pool-size
      minimum-idle: 5
      #最大连接数,小于等于0会被重置为默认值10,大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      pool-name: HikariPool-ai-service

  ai:
    # qwen模型 符合openai规范
    openai:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        completions-path: /chat/completions
        options:
          model: qwen3-max
          temperature: 0.7 # 0-2 随机性 数字越高越有创造性
      # 文本向量模型
      embedding:
        embeddings-path: /embeddings
        options:
          model: text-embedding-v4

    # ollama本地模型
#    ollama:
#      base-url: http://127.0.0.1:11434
#      chat:
#        model: qwen3:8b
#        options:
#          temperature: 0.7

    # 记忆 数据库存储
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/sql/schema-mysql.sql

    # 向量数据库
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index-1
        dimensions: 1024
        similarity: cosine

    # mcp
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: SYNC  # or ASYNC for reactive applications
        toolcallback:
          enabled: true
        # sse
        sse:
          connections:
            # MCP Server名称
            mcp-server-weather:
              url: http://localhost:8082
        # stdio
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: debug

# 可观测性配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
